version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./app/data:/var/lib/data
    env_file: .env
    ports:
      - "8080:8080"
