version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: "aODIJfe3"
    #   MYSQL_DATABASE: financedata
    #   MYSQL_PASSWORD: "aODIJfe3"
    env_file:
      path: ./.env
    required: true 
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      # - ./app/backup:/backup

  web:
    build: ./app
    restart: always
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=mysql+pymysql://root:aODIJfe3@db:3306/financedata
    env_file:
      path: ./.env
    ports:
      - "8080:8080"