version: '3.8'

services:

  app:
    build:
      context: ./         # Path to the directory containing the web Dockerfile
      dockerfile: ./app/Dockerfile
    restart: always
    volumes:
      - ./data:/var/lib/data
    env_file: .env
    ports:
      - "8080:8080"
