services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./app/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:aODIJfe3@db:3306/financedata
    # ports:
    #   - containerPort: 8080

  - type: worker 
    name: db
    env: docker
    dockerfilePath: ./db/Dockerfile
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: aODIJfe3
      - key: MYSQL_DATABASE
        value: financedata
      - key: MYSQL_PASSWORD
        value: aODIJfe3
    # ports:
    #   - containerPort: 3306
    # volumes:
    #   - name: mysql-data
    #     path: /var/lib/mysql
