services:
  - type: web
    name: finance-api
    env: docker
    dockerContext: .
    dockerfilePath: ./app/Dockerfile
    autoDeploy: false
    plan: starter
    disk:
      name: data
      mountPath: ./data:/var/lib/data
      sizeGB: 1
    region: singapore
    envVars:
      - key: DATA_PATH
        value: /var/lib/data
    # envVars:
    #   - fromGroup: main-env
    # envVarGroups:
    #   - name: main-env
    #     file: .env
    # ports:
    #   - containerPort: 8080
