services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./app/Dockerfile
    autoDeploy: true
    envVars:
    - fromGroup: main-env
    # ports:
    #   - containerPort: 8080

  - type: pserv
    name: db
    plan: standard
    env: docker
    dockerfilePath: ./db/Dockerfile
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
    - fromGroup: main-env 
    # ports:
    #   - containerPort: 3306

envVarGroups :
  - name: main-env
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:aODIJfe3@44.226.145.213:3306/financedata
      - key: MYSQL_ROOT_PASSWORD
        value: aODIJfe3
      - key: MYSQL_DATABASE
        value: financedata
      - key: MYSQL_PASSWORD
        value: aODIJfe3