services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./app/Dockerfile
    autoDeploy: false
    plan:free
    disk:
      name: data
      mountPath: /var/lib/data
      sizeGB: 1
    envVars:
      - key: DATA_PATH
        value: /var/lib/data
    # ports:
    #   - containerPort: 8080