services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./app/Dockerfile
    autoDeploy: false
    # disk:
    #   name: data
    #   mountPath: /var/lib/data
    #   sizeGB: 5
    envVars:
    - fromGroup: main-env
    # ports:
    #   - containerPort: 8080

envVarGroups :
  - name: main-env
    envVars:
      - key: DATA_PATH
        value: /var/lib/data