# Use an official MySQL image from the Docker Hub
FROM mysql:latest

# # Set the root password for MySQL (change 'your_password' to your desired password)
# ENV MYSQL_ROOT_PASSWORD=your_password

# Expose the MySQL port
EXPOSE 3306

# (Optional) Set the character set and collation for the MySQL server
# ENV MYSQL_DATABASE=your_database
# ENV MYSQL_USER=your_username
# ENV MYSQL_PASSWORD=your_password
# ENV MYSQL_CHARACTER_SET=utf8mb4
# ENV MYSQL_COLLATION=utf8mb4_unicode_ci
